### ISSUE TITLE
[EU] Unable to set rear window/side mirror and steering wheel heating 

### ISSUE THREAD

**Issue by andyearnshaw** [Hacksore/bluelinky#139]
**Describe the bug**
When calling `start()` for climate control in the EU, it doesn't appear to be possible to activate rear window (and side mirror) heating, or the steering wheel heating. The [documentation](https://hacksore.github.io/bluelinky-docs/docs/api-reference#start) is incorrect and doesn't match the [implementation](https://github.com/Hacksore/bluelinky/blob/97730dc8df9d6a92e42951b181da272316cee04c/src/vehicles/european.vehicle.ts#L38), but coding according to the implementation doesn't work either.

**Usefull info(please complete the following information):**
 - OS: N/A
 - Bluelinky Version: v7.1.0
 - Region: EU

**Additional context**
I'm testing on my own vehicle, a Hyundai Kona EV (2021).

It's worth noting also that the current implementation specifies `defrost` which maps to `defrost`, and `windscreenHeating` which maps to `heating1`, but in the Blue Link app, 'Defrost' is identified by a windscreen heating symbol. `windscreenHeating` is probably not the correct term to use for `heating1`, but I don't know this for sure (and it doesn't work for me anyway).

**Comment by andyearnshaw** [comment]
Here's an image of the options available in the app:

![Screenshot_20210420-120920_Bluelink.jpg](https://user-images.githubusercontent.com/1826067/115386479-57e82300-a1d1-11eb-8dbb-4c54471722da.jpg)

**Comment by PierreLevres** [comment]
I can concur on the logic about the windscreen heating vs defrost vs heating1 remarks.
For me, heating1 (rear window, mirrors, steeringwheel) only work if defrost is selected.
If you send defrost=true and heating1 = 1, your car will be a heated.
![IMG_6612](https://user-images.githubusercontent.com/62832923/115443521-a9b19d00-a213-11eb-8b11-86689b6c9250.jpeg)

**Comment by andyearnshaw** [comment]
This is what I'm sending:

```javascript
  const response = await vehicle.start({
    airCtrl: true,
    defrost: true,
    heating1: 1
  });
```

This turns on the air conditioning and the windscreen defrost but not the rear window/side mirror or steering wheel heater.

**Comment by PierreLevres** [comment]
Since you are in the EU, you seem to be missing “temperature" and “unit" in your call.


This config object needs to be passed to the EU-vehicle
public async start(config: VehicleClimateOptions)
Where this config object is defined as:
export interface VehicleClimateOptions {
  defrost: boolean;
  windscreenHeating: boolean;
  temperature: number;
  unit: string;
}
In the  EU-vehicle-code this config object is mapped to the actual API json-object for the call to the server :
body: {
  action: 'start',
  hvacType: 0,
  options: {
    defrost: config.defrost,
    heating1: config.windscreenHeating ? 1 : 0,
  },
  tempCode: celciusToTempCode(config.temperature),
  unit: config.unit,
},

Underneath payload in Node-Red turns on air conditioning, the windscreen defrost and also the rear window/side mirror and steering wheel heater, as you might have seen in my screendump yesterday:
msg.payload = {
    "windscreenHeating”:true,
    "defrost”:true,
    "temperature”:22,
    "unit": "C",
}


(Note: My UVO app is actually sending hvacType: 1, but nevertheless it works)

**Comment by andyearnshaw** [comment]
Yep, that worked. I had tried this before without the `unit` parameter and I think that's what stopped it from working. Strangely, air con switched on without passing temperature, which is why I was confused and thought `airCtrl` was working for me.

So it looks like the real issue is that the documentation is not correct for EU regions (or that the implementation is different for the EU region than the US and Canada regions).

**Comment by Hacksore** [comment]
Yeah, I release think we need to standardize the inputs across all regions so there is no more bad documentation or guesswork.

Let's make that a stretch goal for 8.x release, going to close this issue as a solution was found.
