### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by jaroslawsky** [Hacksore/bluelinky#199]
**Describe the bug**
Since today getVehicle returns an error. Until yesterday everything worked.

**Usefull info(please complete the following information):**
 - OS: Linux
 - Bluelinky Version v7.6.2
 - Region: EU 
 - Brand: hyundai

**Additional context**
Error message:
[ManagedBluelinkyError]: @EuropeController.login: [401] Unauthorized on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/spa/notifications/register - {"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id. - 37641.891000032425","msgId":"ec2a2f9d-6d58-4f1f-a428-4f780c6a4e47"}

**Comment by jaroslawsky** [comment]
Correction:
It's not the getVehicle call. The error comes when starting the server. So it's the instantiation of the BlueLinky object.

**Comment by Hacksore** [comment]
Yeah, auth seems to have changed and we are discussing the solution on discord in this thread. 

https://discord.com/channels/652755205041029120/940144903441244210

**Comment by Hacksore** [comment]
I believe it's fixed with https://github.com/Hacksore/bluelinky/commit/4c7efb6ea6726175936fab5ea8827e56aa9c3553 - will see if I can get a patch out today with this as well.

**Comment by torsten3009** [comment]
since two days again same error with version 2.2.2 - first it was working with this version

`@EuropeVehicle.status: [401] Unauthorized on [GET] https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/xxxxxxxx/status - {"retCode":"F","resCode":"4017","resMsg":"Invalid request value - Invalid Application Id. - 80825.48399996758","msgId":"e4ddfd6c-9108-4c16-a5b3-cf1b63f74715"}`
