### ISSUE TITLE
Kona EV Remote Start Failing

### ISSUE THREAD

**Issue by ErnieErnesto** [Hacksore/bluelinky#235]
**Describe the bug**
Hello all,
    Im using the HomeBridge Hyundai BlueLink plugin. Lock/Unlock work for the vehicle but remote start do not. It is a 2022 Kona EV. It has never worked since I installed the plugin in April 2022.
![CAF08F52-C118-47ED-9AA2-873D89074EB5](https://user-images.githubusercontent.com/118992063/210003105-084cc2f5-f89e-4a81-9da4-2a88283a2292.jpeg)

**Usefull info(please complete the following information):**
 - OS: Homebridge
 - Bluelinky Version no it sure, guessing latest?
 - Region: US
 - Brand: Hyundai

**Additional context**

**Comment by Hacksore** [comment]
It's probably because a full EV has a different concept of starting and it's more just setting the climate control.

This endpoint we use for US/ICE perhaps just doesn't work for an EV.
https://github.com/Hacksore/bluelinky/blob/22c3d8ed505cb26669eaf624e0142ca46745f22a/src/vehicles/american.vehicle.ts#L130

**Comment by ErnieErnesto** [comment]
Thats a bummer 😞. Thanks for responding.

**Comment by Hacksore** [comment]
Related issue from another project

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/400

**Comment by Hacksore** [comment]
Another related issue https://github.com/Hacksore/bluelinky/issues/221

Going to close this issue in favor of that one.
