### ISSUE TITLE
Raw Payload

### ISSUE THREAD

**Issue by lyledean1** [Hacksore/bluelinky#44]
For each endpoint, do you have an example of the raw payload (with sensitive information removed) ?

**Comment by Hacksore** [comment]
Since the project has grown we don't have this all organized that well. I can supply most of the stuff for the US but since I don't have access to other regions with real data I'd have to let the community help out here.

However, with that being said we are trying to streamline the developer integration process to make responses consistent across all regions.

So for example, if I wanted to grab say the hood state, I would do this code regardless of region.

```ts
const doorStatus = await vehicle.status().chassis.hoodOpen
```

**Comment by Hacksore** [comment]
You can find at least some data from the raw status output for both the US and EU regions.

https://github.com/Hacksore/bluelinky/tree/master/__tests__/mock
