### ISSUE TITLE
Support the Korea Bluelink

### ISSUE THREAD

**Issue by myhdh10** [Hacksore/bluelinky#71]
Hello there.
I wanna use yours 👍 How can I help you the making of the Korea Bluelink?

**Comment by Hacksore** [comment]
@myhdh10 we'd need you or someone in Korea to inspect the network requests and share the results with sensitive information removed. If that person could implement the code as we would be helpful.

A good start for supporting this region would be to have the following commands possible.

- Lock/Unlock
- Start/Stop

If you are not familiar with getting the network requests reversed we might need to find someone who can assist.

**Comment by myhdh10** [comment]
@Hacksore thx to reply. Korea Bluelink is controled only by the android app. I can handle a packet using wireshark app. is this right to method?

**Comment by Hacksore** [comment]
Wireshark might work but this is what I do.

https://docs.google.com/document/d/1q0Pz2t5Gmt-vv8z-2Yswhvg2x9B2f3d1vjpkIjt9EfQ/edit?usp=sharing

**Comment by myhdh10** [comment]
Okay, I try do this. I have things to your docs needs. and a little Java knowledge.

**Comment by Hacksore** [comment]
@myhdh10 Any progress on this effort?

**Comment by toraidl** [comment]
Hi @Hacksore, 
First of all, Thank you so much for your work . 
I am trying to add my sonota 10th gen(**China editon**) remote feature to home assistant , because I can not use bluelink with both my iPhone and Andord rooted. 
I have followed your instruction to bypass root check, and ssl pinning but got stuck. 
I took off the protective shell succesfully, and found out that the code is not obfuscated. 

But I don't know how to write the correct frida JS code. 

![image](https://user-images.githubusercontent.com/3390079/98343084-414b7680-204c-11eb-8f8a-ab40ee60387a.png)


`package com.ubivelox.bluelink_c.custom.util;

import java.io.File;
import java.io.IOException;

public class CommonUtil$RootUtil {
   public static boolean isDeviceRooted() {
      String[] var0 = new String[]{"/system/bin/su", "/system/xbin/su", "/system/bin/Busybox", "/system/xbin/Busybox", "/system/bin/Tegrak", "/system/xbin/Tegrak", "/system/app/SuperUser.apk", "/system/app/Unroot.apk", "/system/app/Reboot.apk", "/system/app/Fakeroot.apk"};
      int var1 = 0;

      boolean var2;
      label58: {
         try {
            Runtime.getRuntime().exec("su");
         } catch (IOException var12) {
            var12.printStackTrace();
            var2 = false;
            break label58;
         }

         var2 = true;
      }

      boolean var4 = var2;
      if (!var2) {
         var4 = var2;

         boolean var10001;
         int var5;
         try {
            var5 = var0.length;
         } catch (Exception var11) {
            var10001 = false;
            return var4;
         }

         while(true) {
            var4 = var2;
            if (var1 >= var5) {
               break;
            }

            String var6 = var0[var1];
            var4 = var2;

            File var3;
            try {
               var3 = new File;
            } catch (Exception var10) {
               var10001 = false;
               break;
            }

            var4 = var2;

            try {
               var3.<init>(var6);
            } catch (Exception var9) {
               var10001 = false;
               break;
            }

            var4 = var2;

            boolean var7;
            try {
               var7 = var3.exists();
            } catch (Exception var8) {
               var10001 = false;
               break;
            }

            if (var7) {
               var2 = true;
            }

            ++var1;
         }
      }

      return var4;
   }
}
`

`package com.ubivelox.bluelink_c.network.sslpinning;

import android.util.Xml;
import java.io.InputStream;
import java.util.LinkedList;
import org.xmlpull.v1.XmlPullParser;

public class JKPinnedPublicKey {
   private static JKPinnedPublicKey instance;
   public LinkedList mPinnedKeys = new LinkedList();

   private JKPinnedPublicKey() {
   }

   public static JKPinnedPublicKey sharedInstance(InputStream var0) {
      if (instance == null) {
         instance = new JKPinnedPublicKey();
         if (var0 != null) {
            instance.loadDefaultPins(var0);
         }
      }

      return instance;
   }

   public boolean isContain(String var1) {
      return this.mPinnedKeys.contains(var1);
   }

   public void loadDefaultPins(InputStream var1) {
      this.mPinnedKeys = new LinkedList();
      XmlPullParser var2 = Xml.newPullParser();

      Exception var10000;
      label36: {
         boolean var10001;
         int var3;
         try {
            var2.setInput(var1, (String)null);
            var3 = var2.getEventType();
         } catch (Exception var6) {
            var10000 = var6;
            var10001 = false;
            break label36;
         }

         while(true) {
            if (var3 == 1) {
               return;
            }

            if (var3 != 0 && var3 == 2) {
               try {
                  if (var2.getName().equalsIgnoreCase("string")) {
                     String var7 = var2.nextText();
                     this.mPinnedKeys.add(var7);
                  }
               } catch (Exception var5) {
                  var10000 = var5;
                  var10001 = false;
                  break;
               }
            }

            try {
               var3 = var2.next();
            } catch (Exception var4) {
               var10000 = var4;
               var10001 = false;
               break;
            }
         }
      }

      Exception var8 = var10000;
      throw new RuntimeException(var8);
   }
}
`
`package com.ubivelox.bluelink_c.network.sslpinning;

import java.net.HttpURLConnection;
import java.net.URL;
import java.security.SecureRandom;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.KeyManager;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;

public class JKPinningConnection {
   JKPinnedPublicKey pinnedPublicKey = null;

   public JKPinningConnection(JKPinnedPublicKey var1) {
      this.pinnedPublicKey = var1;
   }

   public HttpURLConnection createConnection(URL var1) {
      JKPinningTrustManager var2 = new JKPinningTrustManager(this.pinnedPublicKey);
      SSLContext var3 = SSLContext.getInstance("TLS");
      var3.init((KeyManager[])null, new TrustManager[]{var2}, (SecureRandom)null);
      HttpsURLConnection var4 = (HttpsURLConnection)var1.openConnection();
      var4.setSSLSocketFactory(var3.getSocketFactory());
      return var4;
   }

   public SSLSocketFactory getSocketFactory() {
      JKPinningTrustManager var1 = new JKPinningTrustManager(this.pinnedPublicKey);
      SSLContext var2 = SSLContext.getInstance("TLS");
      var2.init((KeyManager[])null, new TrustManager[]{var1}, (SecureRandom)null);
      return var2.getSocketFactory();
   }

   public X509TrustManager getX509TrustManager() {
      return new JKPinningTrustManager(this.pinnedPublicKey);
   }
}
`
`package com.ubivelox.bluelink_c.network.sslpinning;

import com.ubivelox.bluelink_c.util.Common.Base64Util;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Date;
import javax.net.ssl.X509TrustManager;

public class JKPinningTrustManager implements X509TrustManager {
   ArrayList mCache = new ArrayList();
   JKPinnedPublicKey mPinnedKey = null;

   public JKPinningTrustManager(JKPinnedPublicKey var1) {
      this.mPinnedKey = var1;
   }

   private String getSPKIHash(X509Certificate var1) {
      try {
         String var3 = Base64Util.base64Encode(MessageDigest.getInstance("SHA-256").digest(var1.getPublicKey().getEncoded()), 0).trim();
         return var3;
      } catch (NoSuchAlgorithmException var2) {
         throw new CertificateException(var2);
      }
   }

   public void checkClientTrusted(X509Certificate[] var1, String var2) {
      throw new CertificateException("Client certificates not supported!");
   }

   public void checkServerTrusted(X509Certificate[] var1, String var2) {
      int var3 = var1.length;
      int var4 = 0;

      X509Certificate var7;
      while(true) {
         String var5 = null;
         var7 = var5;
         if (var4 >= var3) {
            break;
         }

         var7 = var1[var4];
         Date var6 = var7.getNotAfter();
         if ((new Date()).after(var6)) {
            var7 = var5;
            break;
         }

         if (this.mCache.contains(var7)) {
            return;
         }

         var5 = this.getSPKIHash(var7);
         if (this.mPinnedKey.isContain(var5)) {
            break;
         }

         ++var4;
      }

      if (var7 != null) {
         this.mCache.add(var7);
      } else {
         throw new CertificateException("checkServerTrusted fail");
      }
   }

   public X509Certificate[] getAcceptedIssuers() {
      return new X509Certificate[0];
   }
}
`

Your help will be highlly apprecated. 
PS. the "de-crypted" dex attached. 
[classes.zip](https://github.com/Hacksore/bluelinky/files/5500094/classes.zip)

**Comment by Hacksore** [comment]
@toraidl I'd say this could work from just a glance of the code but can't be 100% sure.

```javascript
Java.perform(function() {
  console.log("======");
  console.log("Test SSL Pin bypass");

  var X509TrustManager = Java.use("javax.net.ssl.X509TrustManager");
  var SSLContext = Java.use("javax.net.ssl.SSLContext");

  // TrustManager (Android < 7)
  var TrustManager = Java.registerClass({
    // Implement a custom TrustManager
    name: "dev.asd.test.TrustManager",
    implements: [X509TrustManager],
    methods: {
      checkClientTrusted: function(chain, authType) {},
      checkServerTrusted: function(chain, authType) {},
      getAcceptedIssuers: function() {
        return [];
      }
    }
  });

  // Prepare the TrustManager array to pass to SSLContext.init()
  var TrustManagers = [TrustManager.$new()];
  // Get a handle on the init() on the SSLContext class
  var SSLContext_init = SSLContext.init.overload(
    "[Ljavax.net.ssl.KeyManager;",
    "[Ljavax.net.ssl.TrustManager;",
    "java.security.SecureRandom"
  );
  try {
    // Override the init method, specifying the custom TrustManager
    SSLContext_init.implementation = function(
      keyManager,
      trustManager,
      secureRandom
    ) {
      console.log("[+] Bypassing Trustmanager (Android < 7) request");
      SSLContext_init.call(this, keyManager, TrustManagers, secureRandom);
    };
  } catch (err) {
    console.log("[-] TrustManager (Android < 7) pinner not found");
    //console.log(err);
  }
})

```

**Comment by Hacksore** [comment]
Closing due to age but if we want to revisit this please reply or open a new issue.
