### ISSUE TITLE
[CA] Incorrect celciusToTempCode() range

### ISSUE THREAD

**Issue by thierryd** [Hacksore/bluelinky#96]
In https://github.com/Hacksore/bluelinky/blob/develop/lib/util.ts, the algorithme doesn't apply to the Canadian vehicle. For the Canadian version, the ranges range is 16..32

Here are some valid values:

- 18 : "04H"
- 21.5 : "0BH"
- 24 : "10H"
- 28 : "18H"
- 32 : "20H"

I validated these values with the JSON sent by the real BlueLink application

**Comment by PierreLevres** [comment]
Two relatively easy functions, hextemp=dec2hex(dectemp*2-32) and dectemp=(hex2dec(hextemp)+32)/2. With of course managing the H added to the end of the Hex string.
In EU and US those functions you must put 28, instead of 32.

But it means that util.ts had to be localized for the regions. So a rather significant change in bluelinky.

Also boundary management needs to be implemented to Util.ts

**Comment by Hacksore** [comment]
I have a branch that aims to try and tackle this if anyone wants to pick it up.

https://github.com/Hacksore/bluelinky/tree/fix-temp-codes

**Comment by neoPix** [comment]
`Kia's stupid temp codes` :rofl:

**Comment by Hacksore** [comment]
My latest unworking changes are in the `develop` branch.

```log
Utility › converts celsius to temp code in CA

expect(received).toEqual(expected) // deep equality

Expected: "06H"
Received: "0H"
```

**Comment by neoPix** [comment]
Took some time to test and fix it in this PR : https://github.com/Hacksore/bluelinky/pull/153
