### ISSUE TITLE
Hyundai API documentation?

### ISSUE THREAD

**Issue by jegelstaff** [Hacksore/bluelinky#97]
Congrats on a very cool project, looks amazing. I'm a new Kona Electric owner, so I'm quite interested in this and can think of a few uses. I am wondering where/how you got the details on the underlying Hyundai API? Did you just trap the network traffic to/from the app? Is there an official Hyundai source for the documentation? I would love to see all of what they expose.

Thank you very much for this. Good luck with it,
--Julian

**Comment by altagir** [comment]
Canadian side was pretty much reverse engineered, by observing traffic and hacking a bit the mobile app.

And pretty much the same with US and Europe. But all different techniques. Endpoints and teams working on those are different.

They showed no interest in solving issues. Canadian mobile app was a disgrace and failed commands multiple time (low timeout in their mobile app). While using the API directly was flawless.

So no, there will never be a documentation on that, and they will refuse to answer your questions on API. even if you pay 10$ monthly for that

Make me think I will stop using Bluelink after the first 2 free years. and maybe switch to another hardware with 5G. not that slow 30s waiting to get anything done.

**Comment by jegelstaff** [comment]
Very interesting. The app does seem pretty flakey. But with an EV the charge management features are particularly useful. Thank you for sharing. Very impressive work.

**Comment by Hacksore** [comment]
Welome to the project @jegelstaff 

Yeah, I reversed the webapp for US first then moved to the mobile app for better coverage. I do find that the service is really lacking its stability overall and at this point only use it because it's free for my terms of the vehicle. 

I just got DroneMobile for another car and it's been quite nice to work with so far. Has it's own project https://github.com/Hacksore/drone-mobile that I'd had little issues reversing as it has a webapp too :).
